### ISSUE TITLE
fillet joints - wrong dimesnions 

### ISSUE THREAD

**Issue by ula-w** [mbartlett21/weld-featurescript#26]
To fillet joints - these are proper dimensions of fillet joint - triangle inscribed in weld connection: 
![image](https://user-images.githubusercontent.com/45488807/49429704-7c323900-f7a9-11e8-89a8-83c2143f713c.png)
And this is how it looks like now:
<img width="1217" alt="pachwina" src="https://user-images.githubusercontent.com/45488807/49429735-8c4a1880-f7a9-11e8-88bc-eb5432d73dfd.PNG">
There is also not possible to choose between "a" dimension and "z" dimension (and this is quite useful)

**Comment by emagdalenaC2i** [comment]
There is another PR that affect UI. Once we can merge #24 I will take care of this one

In other PR I ask about the offset, should add a dimension for that?

It may be better to define an offset for the convex and concave shapes
9808913_orig
image530

**Comment by ula-w** [comment]
This offset depends on weld size, here are some examples according to different standards:
https://app.aws.org/itrends/2010/07/it201007/it0710-23.pdf

**Comment by emagdalenaC2i** [comment]
@ula-w based on this pdf 
Convexity is defined in AWS A3.0:2010, Standard Welding Terms and Definitions, as "the maximum distance from the face of a convex fillet weld perpendicular to a line joining the weld toes"
Represented by the red arows in this image
![captura](https://user-images.githubusercontent.com/24428859/49447372-a6e6b680-f7d6-11e8-8b84-a9458da7f763.PNG)
So lets add first a "Convexity offset" as a distance defined by the user and we could see later if we could improve it

**Comment by ula-w** [comment]
ok, we can add this as defined by user for now, I think it will be easy to change it later.
But I am convinced that this value should be assigned (probably in this csv file with production plant).
In the same pdf you can see that its value varies depending on standard, but in general depends on some other parameter:
![image](https://user-images.githubusercontent.com/45488807/49473696-0e225c00-f813-11e8-87c9-77cecb1192e0.png)

As a constructor I must say I have never thought of looking for such parameter while indicating welds on drawings. And I belive this custom feature should make life easier ;)
